### ISSUE TITLE
ERROR Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?

### ISSUE THREAD

**Issue by jdavidhermoso** [formql/formql#10]
Hi!

I'm probably making something bad, but I can't make the <formql> componentn work.

I'm getting an error: `No component factory found for undefined. Did you add it to @NgModule.entryComponents`.

I am preparing a public report to illustrate the issue.

Thanks in advance.

**Comment by jstoppa** [comment]
issue transferred to right repo

**Comment by jdavidhermoso** [comment]
Hi, @jstoppa!

Thank you so much for your support!
I appreciate it so much!

**Comment by jstoppa** [comment]
closing this for now, if you have any other question/problem please raise another issue
