### ISSUE TITLE
Console throws an error when changing components in FormQL editor

### ISSUE THREAD

**Issue by jstoppa** [formql/formql#3]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Changing components in FormQL Editor throws an error if the target components has actions and the previous doesn't implement actions.
E.g. Moving from FormQLCheckboxComponent to FormQLButtonComponent
![image](https://user-images.githubusercontent.com/1074171/55995104-8a3e1c00-5cab-11e9-9ffe-31e238217d41.png)

* **What is the expected behavior?**
Not expecting any error in the console

* **Please tell us about your environment:**
Windows 
  
  - Version: 0.3.1
  - Browser: Chrome

**Comment by formql** [comment]
fixed in release 0.3.2
