### ISSUE TITLE
 I'm using the example to start with formql but it doesn't display the values ​​in the browser with redux

### ISSUE THREAD

**Issue by LucianViana** [formql/formql#58]
I can't see the content of variables with redux, as redux doesn't work with ngrx 7, only with previous versions, is this correct?

**Comment by jstoppa** [comment]
formql doesn't use ngrx any more, the initial prototype was built witn nrgx but it got removed on the initial realease, it just uses RxJS to handle the state.
There will be more improvements coming in soon with will help with looking at the state in real time
